service: my-first-app-artsiom

frameworkVersion: '2'

plugins:
  - serverless-finch
 
custom:
  client:
    bucketName: my-first-app-artsiom
    distributionFolder: build

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1